// Package tbdb
// Code generated by github.com/qoinlyid/qore; DO NOT EDIT.
// Code generated by github.com/qoinlyid/qore; DO NOT EDIT.
// Code generated by github.com/qoinlyid/qore; DO NOT EDIT.
package tbdb

import "github.com/qoinlyid/qore"

// Code generated by github.com/qoinlyid/qore; DO NOT EDIT.
// instanceGen defines Cache dependency singleton.
type instanceGen struct {
	// Priority of open-close dependency.
	priority int
}

// Code generated by github.com/qoinlyid/qore; DO NOT EDIT.
// Compile time check Cache Instance implements qore.Dependency.
var _ qore.Dependency = (*Instance)(nil)

// Code generated by github.com/qoinlyid/qore; DO NOT EDIT.
// Name returns dependency name.
func (i *Instance) Name() string { return "TBDB" }

// Code generated by github.com/qoinlyid/qore; DO NOT EDIT.
// Priority returns dependency open-close priority.
func (i *Instance) Priority() int { return i.priority }
